### ISSUE TITLE
ch.njol.skript.SkriptAPIException: No class info found for uuid

### ISSUE THREAD

**Issue by Zulfen** [Skungee/Skungee-2.0.0#1]
Hey! Was just testing the latest release of Skungee 2.0 (alpha2), and on every script I written, even your example script you supplied on the releases page, this still occurs. Here is the stacktrace:

**https://pastebin.com/bFVn1C3B**

_Here are all the versions:_
```
>.... [19:35:10 ERROR]: #!#! Version Information:
>.... [19:35:10 ERROR]: #!#! Skript: 2.5-alpha4 (latest)
>.... [19:35:10 ERROR]: #!#! Flavor: skriptlang-github
>.... [19:35:10 ERROR]: #!#! Date: 2020-06-24
>.... [19:35:10 ERROR]: #!#! Bukkit: 1.15.2-R0.1-SNAPSHOT
>.... [19:35:10 ERROR]: #!#! Minecraft: 1.15.2
>.... [19:35:10 ERROR]: #!#! Java: 1.8.0_242 (OpenJDK 64-Bit Server VM 25.242-b08)
>.... [19:35:10 ERROR]: #!#! OS: Linux amd64 4.15.0-38-generic
>.... [19:35:10 ERROR]: #!#!
>.... [19:35:10 ERROR]: #!#! Server platform: Paper (Note: build 373)
```
...and the line it throws an exception on:

```>.... [19:35:10 ERROR]: #!#! Current node: set slot {_slot} of {_inventory} to skull of loop-skungeeplayer named "%loop-skungeeplayer%" (test.sk, line 16)```

No effects that use a player expression work (you can probably tell from the error itself)

If you are wondering, 1.0.14 does not have this issue and it only occurs on 2.0.

**Comment by TheLimeGlass** [comment]
Fixed in 2.0.0-ALPHA-3.

Thanks for Alpha testing 2.0.0!
