### ISSUE TITLE
Can not delete a network variable

### ISSUE THREAD

**Issue by ardaok** [Skungee/Skungee-2.0.0#10]
## Description
!delete network variable {asdasd}
does not work.

## Actual Behavior
Does nothing

## Expected Behavior
Deletes variable from csv lol

## Steps to Reproduce the Problem
1. Set a network variable, then try to delete it with !delete network variable {asdasd}

## Specifications
Skungee Version: Lastest
Platform and Version: Paper Spigot 1.16.1

**Comment by TheLimeGlass** [comment]
Fixed in 2.0.0-ALPHA-7
