### ISSUE TITLE
Minecraft 1.8.x and e.g. 1.16.x in one network with the latest skungee ver.?

### ISSUE THREAD

**Issue by Allesco** [Skungee/Skungee-2.0.0#103]
## What you need help with
Hi,
how can I run multiple Minecraft servers in one bungeecord network with different minecraft versions (e.g. 1.8.x and 1.16) with skungee? I heard that you need java 8 to run a 1.8 mc server, but java 16 is required for the new skungee versions.
So is there a possibility to connect both servers with the new skungee version?

## Specifications
Skungee Version: latest
Proxy Platform and Version: 
System/Panel (if applicable):

**Comment by TheLimeGlass** [comment]
yes the bungeecord version doesn't matter, it's all been the same api
