### ISSUE TITLE
Skungee Messaging Elements

### ISSUE THREAD

**Issue by shivasuc** [Skungee/Skungee-2.0.0#11]
**Is your feature request related to a problem? Please describe.**
Since skungee can now communicate a network of servers really fast, it would be great if there was a way to
use this messaging system freely trough skript elements.

**Describe the suggestion you'd like**
The messaging system would work in a send/receive way.
Example effect to send a message to one or more servers:

`send [skungee] message %string% to %servers%`

then the target servers can hanlde this message using the event

`on skungee message:`

the event values could be:
message
sender (server who sent the message)

**Additional context**
it would be up to the user to decide what they want to do with this, but it opens the door to some
cool creations and freedom to create connected server systems.

**Comment by TheLimeGlass** [comment]
Added in  2.0.0-ALPHA-19
