### ISSUE TITLE
1.8 client doesnt connect to proxy

### ISSUE THREAD

**Issue by LeckererSandwich** [Skungee/Skungee-2.0.0#140]
I got an 1.17 and an 1.8 server both with the same default config both say they are connected but the 1.8 server just doent connect i just dont understand why the 1.8 server is java 17 and sk 2.6.1

**Comment by TheLimeGlass** [comment]
Using Skungee 2.0.0 doesn't disallow client connects. That'll be your proxy not Skungee if using 2.0.0+
