### ISSUE TITLE
Skungee server execution effect

### ISSUE THREAD

**Issue by ardaok** [Skungee/Skungee-2.0.0#16]
**Is your feature request related to a problem? Please describe.**
Yes, i need to execute commands from my proxy.

**Describe the suggestion you'd like**
(execute|run) (bungee|proxy) command %string% [in [proxy] server(s) %string%]

**Additional context**
I want to execute command in both proxy and other connected servers

**Comment by TheCommander64** [comment]
I also need this for a ranking system using luck perms bungeecord which its commands can only be run through proxy server

**Comment by Deichor** [comment]
We are waiting.

**Comment by hammad-alhassan** [comment]
i also need this and thanks for maintaining and updating skungee

**Comment by TheCommander64** [comment]
If I’m honest I found a second skript addon for bungeecord that does server console stuff, but doesn’t do network variables. So what i did is I have both plugins. Skungee for variables and sending players, the other one does console commands, and looping players so on and so forth

**Comment by TheLimeGlass** [comment]
Added in 2.0.0-BETA-21

`execute command %strings% on %skungeeservers%`
