### ISSUE TITLE
Does Skungee work on minehut

### ISSUE THREAD

**Issue by UnderCurve** [Skungee/Skungee-2.0.0#160]
## What you need help with
I'm just wondering if Skungee would work on minehut with an external backend server

## What you've tried so far
nothing

## Specifications
Skungee Version: latest
Proxy Platform and Version: Velocity (latest)
System/Panel (if applicable): Revivenode/minehut

**Comment by ANDREI12333** [comment]
Using it on Minehut will not work. On Revivenode you must have a port open on the bungeecord and another one on the lobby / backend servers

**Comment by TheLimeGlass** [comment]
no
