### ISSUE TITLE
Skungee not working on pterodactyl

### ISSUE THREAD

**Issue by TheCGuyGitHub** [Skungee/Skungee-2.0.0#185]
## What you need help with
I have skungee installed on a Server with Pterodactyl,
but Skungee isn't working.
When i try to set a Network Variable i always get the **[Skungee] Timed out attempting to send network variable {test}** error

## What you've tried so far
I've tried changing the IP to **172.18.0.1**, and i checked all Ports if they are allowed in ufw and assigend to the servers.
I tried making a Server without Pterodactyl and it worked, but i still want to use Pterodactyl.

## Specifications
Skungee Version: 2.0.0-BETA-5
Proxy Platform and Version: Velocity 3.2.0-SNAPSHOT
System/Panel (if applicable): Pterodactyl

**Comment by Lennord** [comment]
> ## What you need help with
> I have skungee installed on a Server with Pterodactyl, but Skungee isn't working. When i try to set a Network Variable i always get the **[Skungee] Timed out attempting to send network variable {test}** error
> 
> ## What you've tried so far
> I've tried changing the IP to **172.18.0.1**, and i checked all Ports if they are allowed in ufw and assigend to the servers. I tried making a Server without Pterodactyl and it worked, but i still want to use Pterodactyl.
> 
> ## Specifications
> Skungee Version: 2.0.0-BETA-5 Proxy Platform and Version: Velocity 3.2.0-SNAPSHOT System/Panel (if applicable): Pterodactyl

Hello, this problem is completely normal.

In fact, when you restart or turn on the proxy (Bungeecord/Waterfall), you must then restart all the Minecraft Spigot/Paper servers, because otherwise if you don't, the problem may reoccur, in any case it works on my side (Pufferpanel/Pterodactyl and others...).

Thank you for your understanding !

**Comment by TheCGuyGitHub** [comment]
> > ## What you need help with
> > I have skungee installed on a Server with Pterodactyl, but Skungee isn't working. When i try to set a Network Variable i always get the **[Skungee] Timed out attempting to send network variable {test}** error
> > ## What you've tried so far
> > I've tried changing the IP to **172.18.0.1**, and i checked all Ports if they are allowed in ufw and assigend to the servers. I tried making a Server without Pterodactyl and it worked, but i still want to use Pterodactyl.
> > ## Specifications
> > Skungee Version: 2.0.0-BETA-5 Proxy Platform and Version: Velocity 3.2.0-SNAPSHOT System/Panel (if applicable): Pterodactyl
> 
> Hello, this problem is completely normal.
> 
> In fact, when you restart or turn on the proxy (Bungeecord/Waterfall), you must then restart all the Minecraft Spigot/Paper servers, because otherwise if you don't, the problem may reoccur, in any case it works on my side (Pufferpanel/Pterodactyl and others...).
> 
> Thank you for your understanding !

I already tried
