### ISSUE TITLE
Network variables do not work

### ISSUE THREAD

**Issue by ardaok** [Skungee/Skungee-2.0.0#2]
Bungee console.
`Exception in thread "pool-5-thread-1"
15:34:58 [SEVERE] java.lang.NullPointerException
15:34:58 [SEVERE]     at com.skungee.shared.serializers.NetworkVariableSerializer.serialize(NetworkVariableSerializer.java:52)
15:34:58 [SEVERE]     at com.skungee.proxy.handlers.NetworkVariableHandler.lambda$handle$2(NetworkVariableHandler.java:77)
15:34:58 [SEVERE]     at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
15:34:58 [SEVERE]     at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
15:34:58 [SEVERE]     at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
15:34:58 [SEVERE]     at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:899)
15:34:58 [SEVERE]     at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
15:34:58 [SEVERE]     at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
15:34:58 [SEVERE]     at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
15:34:58 [SEVERE]     at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
15:34:58 [SEVERE]     at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
15:34:58 [SEVERE]     at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
15:34:58 [SEVERE]     at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
15:34:58 [SEVERE]     at com.skungee.proxy.handlers.NetworkVariableHandler.handle(NetworkVariableHandler.java:78)`
....

**Comment by TheLimeGlass** [comment]
Ok the issue is because the variable is not set, make sure to set the variable before calling it. The error has been fixed in the next version, and this will just return `<none>`
