### ISSUE TITLE
String to SkungeeServer

### ISSUE THREAD

**Issue by TheLimeGlass** [Skungee/Skungee-2.0.0#21]
## Description
Skript isn't using the String to SkungeeServer converter. Might be a Skript issue. Figure out why, and fix it on Skript or Skungee's side.

```vb
on script load:
    set {_test::*} to proxied players on server "test"
```

## Specifications
Skungee Version: 2.0.0-ALPHA-7
Proxy Platform and Version: Waterfall 1.16-R0.2

**Comment by Anarchick** [comment]
it works only if you use a variable instead of a string
```
set {_test} to "test"
proxied players on server {_test}
```
