### ISSUE TITLE
Network Variable Issue

### ISSUE THREAD

**Issue by SleeziPZ** [Skungee/Skungee-2.0.0#31]
## Description
Whenever I add more than 3 offline players to a network variable list, the list times out and console sends me this message, "[Skungee] Timed out attempting to send network variable {test::*}". But, when I use text in a network variable list, I can add as many values as I want.

## Actual Behavior
Lists times out after more than 3 offline players are added to a network variable list

## Expected Behavior
To be able to add more than 3 offline players in a network variable list

## Steps to Reproduce the Problem
1.Add 3 offline players to a network variable list
2.Add 1 more offline player to a network variable then console error message "[Skungee] Timed out attempting to send network variable {test::*}" is recieved

## Specifications
Skungee Version: 2.0.0-ALPHA-7
Proxy Platform and Version: Waterfall Build #371
System/Panel (if applicable):

**Comment by ArmeaX45** [comment]
Did u find a solution?
