### ISSUE TITLE
Bungeecord message channels

### ISSUE THREAD

**Issue by Hypenexy** [Skungee/Skungee-2.0.0#43]
The feature I would love in Skungee 2 is the bungeecord message channels from Skungee 1

**Comment by TheCommander64** [comment]
This would be greatly appreciated as I am needing to make a cross-network staff chat, and Skungee 1.0.15 will not function for us correctly. @TheLimeGlass

**Comment by TheLimeGlass** [comment]
Added in 2.0.0-ALPHA-19. They're called Signals now.
