### ISSUE TITLE
Skungee not working properly 

### ISSUE THREAD

**Issue by Envqu** [Skungee/Skungee-2.0.0#50]
## Description

I have problem with Skungee and Skungee 2.0.
- Skungee (normal version) not saving my network variables. There is no errors, but connection between servers in console is good. No variables in variables.csv...
- Skunge 2.0 - Only ALPHA-7 working.. When I updated it to ALPHA-9 it can't sync variables (50 errors per minute) and connect to bungee.

## Specifications
Skungee Version: ALPHA-9 and 1.0.15 + older
Proxy Platform and Version: Waterfall 384 (older version also not working) + Paperspigot 390
System/Panel (if applicable): Ubuntu 16.04.7 LTS

**Comment by Envqu** [comment]
Thanks for fast reply and fix

**Comment by TheLimeGlass** [comment]
Variables aren't in 2.0.0 yet
