### ISSUE TITLE
Unable to parse word as a Skungee server if the identifier contains an underscore

### ISSUE THREAD

**Issue by Orendigo** [Skungee/Skungee-2.0.0#51]
## Description
If a server name contains an underscore, it cannot be parsed as a Skungee server.
```
command /test:
	permission: is.op
	trigger:
		# works
		loop all proxied players on server lobby:
			message "%loop-value%" to player
		# does not work
		loop all proxied players on server old_poly:
			message "%loop-value%" to player
```

The only workaround I have found is to instead use the method mentioned in issue #21:
```
command /test:
	permission: is.op
	trigger:
		set {_old_poly} to "old_poly"
		loop all proxied players on server {_old_poly}:
			message "%loop-value%" to player
```

## Screenshots or Errors
Using the first code block above:
![image](https://user-images.githubusercontent.com/5246739/101847483-5f136c00-3b21-11eb-9ece-fc3dae83c350.png)

## Actual Behavior
The script will error on load.  Servers without an underscore in their identifier work fine.

## Expected Behavior
The script parses the server identifier correctly.

## Steps to Reproduce the Problem
1. Create server with an underscore in its identifier.
2. Ensure it is defined with an underscore in the bungee configuration.
3. Attempt to use an expression with the server identifier word parsed as a Skungee server.

## Specifications
Skungee Version: 2.0.0-ALPHA-9
Proxy Platform and Version: Waterfall-388
System/Panel (if applicable): Ubuntu 18.04 using openjdk-11

**Comment by TheLimeGlass** [comment]
Potentially fixed in ALPHA 14
