### ISSUE TITLE
Skungee 1.8.8 Skript PropertyCondition addition

### ISSUE THREAD

**Issue by Redblock6YT** [Skungee/Skungee-2.0.0#63]
Hello,
I keep getting an error while loading Skungee. There is more information below.
Let me know if you need more info.

**Skript Version:**
2.2-dev36

**Minecraft Version:**
Paper 1.8.8

**Skungee Version:**
2.0.0-ALPHA-6

**Error in console:**
https://pastebin.com/RDvsqxiJ

Thanks,
Redblock6

**Comment by TheLimeGlass** [comment]
Skungee 2.0.0 currently doesn't support 1.8 this will be added in the future.

**Comment by TheLimeGlass** [comment]
Fixed in ALPHA-17 https://github.com/Skungee/Skungee-2.0.0/releases/tag/2.0.0-ALPHA-17
