### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by iPlexyOrg** [Skungee/Skungee-2.0.0#64]
name of player's current inventory does not work, when i installed skungee
tab-complete is very buggy,  when i installed skungee

**Comment by TheLimeGlass** [comment]
Skungee doesn't have player's current inventory

**Comment by TheLimeGlass** [comment]
Skungee has nothing that could interfere

**Comment by iPlexyOrg** [comment]
But it is just when i have skungee installed. Otherwise it works fine
