### ISSUE TITLE
Velocity support

### ISSUE THREAD

**Issue by rudde0** [Skungee/Skungee-2.0.0#66]
**Is your feature request related to a problem? Please describe.**
Yes it is. Velocity providing high playercounts in single proxy because of this, it is important.

**Describe the suggestion you'd like**
Skungee should deploy on Velocity proxies.

**Comment by TheLimeGlass** [comment]
It does but there is currently an issue where for some reason it doesn't read it's own Velocity file and would rather throw an error because the Bungee cord class is also compiled in the same jar. Probably a work around somewhere that needs to be implemented.

**Comment by TheLimeGlass** [comment]
Updated to Velocity 1.1.8 and fixed some issues in version 2.0.0-ALPHA-20. Please reset your config.toml.
