### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by iPlexyOrg** [Skungee/Skungee-2.0.0#68]
3rd Try
Do you want to close my ticket a 3rd time?
Its cool that there's nothing with auto complete in Skungee but then explain to me, why the bug is only there, when skungee is installed?
And magically disapears, when i remove Skungee?
With skungee, my autocomplete wont work, without it works

**Comment by TheLimeGlass** [comment]
I don't know dude. You must have also installed something else or changed the auto complete setting in the spigot.yml. Skungee doesn't do anything relating to auto completion.
