### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by elpelirrojo12** [Skungee/Skungee-2.0.0#71]
## Description
Crashes on load

## Screenshots or Errors
https://pastebin.com/cqgA74y7 (it says it's an older version of Skungee but the same happened on the latest version, I was just checking if it would work with an older version)

## Steps to Reproduce the Problem
1. Install the jar on the Spigot server
2. Crashes on load
3.

## Specifications
Skungee Version: 16.2
Proxy Platform and Version: Waterfall (1.8.9)
System/Panel (if applicable): -

**Comment by TheLimeGlass** [comment]
Skungee 2.0.0 only supports Skript 2.3+ currently.

**Comment by TheLimeGlass** [comment]
Fixed in ALPHA-17 https://github.com/Skungee/Skungee-2.0.0/releases/tag/2.0.0-ALPHA-17
