### ISSUE TITLE
[Suggestion] Add Execute Command Bungeecord

### ISSUE THREAD

**Issue by MrFlorentin** [Skungee/Skungee-2.0.0#73]
**Describe the suggestion you'd like**
If its possible to add a way to execute Bungeecord commands.
We can imagine :
- Force player to execute a bungee command
- Make player execute a Bungee command
And others things that can be used in context on commands. 

**Thanks to considere my suggestion !**

**Comment by TheLimeGlass** [comment]
Added in ALPHA-17 https://github.com/Skungee/Skungee-2.0.0/releases/tag/2.0.0-ALPHA-17
