### ISSUE TITLE
Polish symbols error in not skungee skript's

### ISSUE THREAD

**Issue by Galajus** [Skungee/Skungee-2.0.0#75]
I use polish symbols in my skript like śćżźąęó, skungee on start send errors to konsole about that. This is big problem? Maybe can u add ingore options to this error? :D

§7[§6Skungee§7] Charset US-ASCII does not support some symbols in script

**Comment by TheLimeGlass** [comment]
You can change the charset in the configurations

**Comment by TheLimeGlass** [comment]
global scripts disabled in alpha 18 for the time being
