### ISSUE TITLE
Syntax error with Skungee 2.0.0

### ISSUE THREAD

**Issue by Vayune** [Skungee/Skungee-2.0.0#76]
## Description
None of my scripts using Skungee syntax are working.

## Screenshots or Errors
Can't understand syntax in console

## Actual Behavior
Not working at all

## Expected Behavior
Working like in Skungee 1.0.15

## Steps to Reproduce the Problem
1. Write your skript with Skungee 1.0.15 syntax
2. Reload the skript

## Specifications
Skungee Version: 2.0.0 latest alpha
Proxy Platform and Version: Flamecord latest

**Comment by TheLimeGlass** [comment]
Syntax have changed, the word `bungeecord` was replaced with `proxy` you can look through the source code to find syntax until further notice.
