### ISSUE TITLE
How to make spigot skungee connect to a "remote" IP?

### ISSUE THREAD

**Issue by W0lfyZRex** [Skungee/Skungee-2.0.0#86]
## What you need help with

I need to make it so the skungee on spigot connects to the proxy's ip, not a local one.
Both servers are technically on the same machine but I can't get it to work when trying to connect to localhost, 127.0.0.1 or 0.0.0.0. I know that putting the public ip works on Skungee 1.X but on 2.X it tries to "bind" the IP without success, so I'm stuck with Skungee 1.X that has lots of network variables issues like the fact that network variables just don't work anymore when the proxy has been online for more than 10 minutes and things like that.

## What you've tried so far

Inputting multiple local ips like 0.0.0.0, localhost, 127.0.0.1 and some other "local" ips beginning with 172

## Specifications
Skungee Version: 2.0-ALPHA-18
Proxy Platform and Version:  Bungeecord latest (idk the exact version but its the latest)
System/Panel (if applicable): Linux/Pterodactyl (spigot is on pterodactyl, bungee is on straight up linux in a screen)

PS: I know that it's not the latest version of Skungee because I'm on 1.8 (pvp based gamemode, won't upgrade for obvious reasons) and Skript-1.8 still hasn't received an update for Skript 1.6 and latest Skungee requires Java 16 which makes half the plugins break for no reason.

**Comment by TheLimeGlass** [comment]
The latest version is 2.0.0-BETA-1

**Comment by TheLimeGlass** [comment]
I believe you can run it with what ever Skript version.

**Comment by W0lfyZRex** [comment]
2.0.0-BETA-1 requires Java 16 (already tried with Java 11) and plugins break with 16 for some reason

**Comment by TheLimeGlass** [comment]
Latest Skript 2.6-ALPHA-3 works for me.

**Comment by W0lfyZRex** [comment]
Skript no longer supports 1.8 since ages that’s why I’m using a fork made for 1.8 but the owner of the fork has not updated to 1.6 yet so I’m stuck with 1.5.3 for now

**Comment by W0lfyZRex** [comment]
And I can’t just upgrade to newer Minecraft versions because the whole point of the minigame is pvp and even with 2 billion plugins to “revert” pvp, it still feels way less smooth and lots of tryhards won’t like it.

**Comment by TheLimeGlass** [comment]
Duplicate #103

**Comment by Allesco** [comment]
@TheLimeGlass any idea to this issue? It's still there for me.
